GT-1753 remove favorited resources cache from tool cards
CruGlobal/godtools-swift pull request #1298
Opened 2022-08-11 20:17 UTC by rachaelblue

2022-08-12 13:01 UTC, levieggertcru requested changes
Hey @rachaelblue I did a quick look over of this PR and I noticed some additional work that isn't needed for [GT-1753](https://jira.cru.org/browse/GT-1753).  Mainly around adding the extra ```GetAllFavoritedToolIDsUseCase``` and the sorting of resource ids for favorited tools.  Favorited tools for now are sorted by the creation (favorited) date.  In the future there will be some additional rules around how those are sorted, such as by a user sort order.

The main focus of this task was removing the FavoritedResourcesCache dependency in place of those listed UseCases.  I should have also mentioned the ```GetAllFavoritedToolsUseCase``` in the ticket because it looks like that will be needed in the ```BaseFavoriteToolsViewModel```.  I like the ```ToggleToolFavoritedUseCase```, that will be helpful in cutting down the need to inject 2 use cases.


<img width="895" alt="FavoritedResourcesCache-Dependency" src="https://user-images.githubusercontent.com/59846460/184358667-c85d16b1-f47a-4d3e-8d94-30e73a6ca7a5.png">

2022-08-12 14:26 UTC, rachaelblue commented
Hey @levieggertcru, sorry I probably should've clarified what I did here.  

- Renamed `GetAllFavoritedToolsUseCase` --> `GetAllFavoritedToolIDsUseCase`
- Recreated `GetAllFavoritedToolsUseCase` to return `ResourceModel`, since the original version just returns `FavoritedResourceModel` (which is essentially just the tool ID, not the actual tool)

`BaseFavoriteToolsViewModel` needs `ResourceModel` objects, not just the IDs, so I thought it made sense to rename so it's clear what you're actually getting back from the use case.  So, `GetAllFavoritedToolIDsUseCase` is your existing code, and `GetAllFavoritedToolsUseCase` is new code, but it uses `GetAllFavoritedToolIDsUseCase` inside it.  Does that make sense?

2022-08-12 17:25 UTC, levieggertcru commented
Hey @rachaelblue on ```develop``` see line 182 of ```BaseFavoriteToolsViewModel``` https://github.com/CruGlobal/godtools-swift/blob/develop/godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift#L182 and it's fetching the ```FavoritedResourceModel``` objects.
And then line 32 of ```GetAllFavoritedToolsUseCase``` and it's returning ```FavoritedResourceModel```.

Eventually ```GetAllFavoritedToolsUseCase``` will return a ```ToolDomainModel```.  I just didn't want to introduce those changes yet until the refactor because it's going to be a lot more work involved.

I should have explained that better in the Jira task.

2022-08-12 19:39 UTC, rachaelblue commented
@levieggertcru ok gotcha, I'll switch it back then and leave the logic to fetch the tool itself inside the base class.

2022-08-15 15:43 UTC, levieggertcru requested changes

2022-08-15 15:43 UTC, levieggertcru commented on godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
> +        isFavorited = getToolIsFavoritedUseCase.getToolIsFavorited(tool: resource)
Hey @rachaelblue this shouldn't be needed now that you are subscribed to a publisher below in the setupBinding() method.
```
getToolIsFavoritedUseCase.getToolIsFavoritedPublisher(tool: resource)
            .receive(on: DispatchQueue.main)
            .assign(to: \.isFavorited, on: self)
            .store(in: &cancellables)
```

2022-08-15 19:08 UTC, levieggertcru approved these changes

2022-08-15 19:34 UTC, merged